[workspace]
members = [
    "utils",
    "data",
    "components",
    "app",
    "web"
]
[workspace.package]
version = "0.1.0"

[workspace.dependencies]
csv = "1.1"
gloo-console = "0.2"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "Window",
    "HtmlSelectElement",
    "Event",
    "MouseEvent",
] }
yew = { version = "0.20", features = ["csr"] }