[package]
name = "lat-long-finder"
edition = "2021"
version.workspace = true

[dependencies]
structopt = { workspace = true }
tokio = { workspace = true }
utils = { path = "../utils", features = ["no-wasm"] }
thiserror = { workspace = true }