[package]
name = "app"
version.workspace = true
edition = "2021"

[dependencies]
yew = { workspace = true }
components = { path = "../components" }
data = { path = "../data" }
utils = { path = "../utils" }
gloo-console = { workspace = true }