[package]
name = "components"
version.workspace = true
edition = "2021"

[dependencies]
yew = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
data = { path = "../data" }