[package]
name = "utils"
version.workspace = true
edition = "2021"

[dependencies]
csv = { workspace = true }
data = { path = "../data" }
reqwest = { workspace = true, features=["blocking"] }
serde_json = { workspace = true }
