name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/rust-wasm-builder:latest
  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/rust-wasm-builder:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2024-06-21
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
      - name: Run build script
        run: /app/build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CALIFORNIA_RESERVOIR_ACTION_TOKEN }}
      - name: Run push script
        run: /app/push.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CALIFORNIA_RESERVOIR_ACTION_TOKEN }}
